version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sakura_food
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://user:0@localhost/sakura_food
      BOT_TOKEN: your-bot-token

volumes:
  postgres_data:
